# ffmesh 测试配置文件

# 节点唯一标识符（留空测试自动生成）
node_id: ""

# 代理配置 - 本地TCP端口代理到远程节点
proxies:
  - local_port: 8080
    target_node_id: "f6g7h8i9j0"
    target_address: "192.168.1.100:3000"
    name: "web-service"

# QUIC配置
quic:
  # 本地QUIC监听端口
  listen_port: 4242
  
  # 上级节点配置（可以有0-2个）
  upstreams:
    - node_id: "upstream01"
      address: "192.168.1.1:4242"
      name: "主节点" 